### ISSUE TITLE
astronomer image

### ISSUE THREAD

**Issue by matt-winkler** [sungchun12/airflow-dbt-cloud#11]
Hey @sungchun12 I kept getting this error with the image currently listed in this repo. 

```
Invalid Semantic Version
Env file ".env" found. Loading...
Invalid Semantic Version
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1422eb8]

goroutine 1 [running]:
github.com/Masterminds/semver.(*Version).Major(...)
        /Users/koenitzer/go/pkg/mod/github.com/!masterminds/semver@v1.5.0/version.go:131
github.com/astronomer/cloud-cli/pkg/util.Coerce({0x0, 0x5})
        /Users/koenitzer/go/src/github.com/astronomer/cloud-cli/pkg/util/util.go:18 +0x78
github.com/astronomer/cloud-cli/airflow.CheckRuntimeVersion({0xc0006f3ad0, 0xc}, {0x1dfb7f3, 0x8})
        /Users/koenitzer/go/src/github.com/astronomer/cloud-cli/airflow/docker.go:735 +0x21c
github.com/astronomer/cloud-cli/airflow.generateConfig({0xc00003f4e8, 0x18}, {0xc000048044, 0x2e}, {0x1df6c7e, 0x4}, {0x0, 0x0}, {0x0, 0x0}, ...)
        /Users/koenitzer/go/src/github.com/astronomer/cloud-cli/airflow/docker.go:165 +0x2de
github.com/astronomer/cloud-cli/airflow.createProject({0xc00003f4e8, 0x6}, {0xc000048044, 0x2e}, {0x1df6c7e, 0x2}, {0x0, 0x1}, {0x0, 0x0}, ...)
        /Users/koenitzer/go/src/github.com/astronomer/cloud-cli/airflow/docker.go:201 +0x7f
github.com/astronomer/cloud-cli/airflow.Start({0xc000048044, 0x2e}, {0xc0002dfdc0, 0xc0002dfd98}, {0x1df6c7e, 0x4})
        /Users/koenitzer/go/src/github.com/astronomer/cloud-cli/airflow/docker.go:285 +0x125
github.com/astronomer/cloud-cli/cmd.airflowStart(0xc0003b2a00, {0x28ce678, 0x0, 0x0})
        /Users/koenitzer/go/src/github.com/astronomer/cloud-cli/cmd/airflow.go:335 +0x86
github.com/spf13/cobra.(*Command).execute(0xc0003b2a00, {0x28ce678, 0x0, 0x0})
        /Users/koenitzer/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004c5400)
        /Users/koenitzer/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/koenitzer/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
        /Users/koenitzer/go/src/github.com/astronomer/cloud-cli/main.go:16 +0x31
```

After some googling and landing on this [page](https://forum.astronomer.io/t/unable-to-start-airflow-locally-after-migrating-from-astro-to-astrocloud/1988) I updated the image to `quay.io/astronomer/astro-runtime:4.2.6` which appears to be working.

**Comment by sungchun12** [comment]
Thank you. I'll fix this next week!
